### ISSUE TITLE
spotify-this-song - White Space on Search fails.

### ISSUE THREAD

**Issue by fullers** [fullers/liri-node-app#1]
Need to fix this issue if possible: 

If you input the command like:
node liri.js spotify-this-song The Sign   (Does not work)

node liri.js spotify-this-song "The Sign" (Works)

**Comment by fullers** [comment]
ITSFULLERSMAC:liri-node-app fullers$ node liri.js spotify-this-song The Sign
/Users/fullers/Desktop/Bootcamp/Homework10/liri-node-app/liri.js:74
        for (var i=0; i < data.tracks.items.length; i++) {
                                     ^

TypeError: Cannot read property 'items' of undefined
    at /Users/fullers/Desktop/Bootcamp/Homework10/liri-node-app/liri.js:74:38
    at IncomingMessage.<anonymous> (/Users/fullers/Desktop/Bootcamp/Homework10/liri-node-app/node_modules/spotify/lib/spotify/Spotify.js:29:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ITSFULLERSMAC:liri-node-app fullers$
